---
# tasks file for Apache Zookeeper


- name: "Install OpenJDK Runtime Environment {{ java_version }}"
  yum:
    name: java-{{ java_version }}-openjdk
    state: present
  tags:
    - zookeeper
    - zookeeper_install
    - zookeeper_java

- name: Install zktop
  pip:
    name: zktop
  tags:
    - zookeeper
    - zookeeper_install
    - zookeeper_utills


- name: Install some utilities
  yum:
    name:
      - wget
      - tar
      - net-tools
      - netcat
      #- ca-certificates
    state: latest
  tags:
    - zookeeper
    - zookeeper_install
    - zookeeper_utills


- name: Include configuration tasks
  include: "config.yml"
  tags:
    - zookeeper
    - zookeeper_config


- name: Include Apache Zookeeper tasks
  include: "zookeeper.yml"
  tags:
    - zookeeper
    - zookeeper_install
