---

- name: restart egi consumer
  service: name=argo-egi-consumer state=restarted

- name: restart all consumers
  service: name=argo-{{ item.key | lower }}-consumer state=restarted
  with_dict: tenants

