---
  
- name: restart egi consumer
  service: name=argo-egi-consumer state=restarted

- name: restart all consumers
  service: name=argo-{{ item.key | lower }}-consumer state=restarted
  with_dict: " {{ consumer_tenants }} "

# TODO: Make following handler task tenant unaware
- name: restart all non egi consumers
  service: name=argo-{{ item.key | lower }}-consumer state=restarted
  with_dict: " {{ consumer_tenants }} "
  when: item.key|lower != "egi"
