---

- name: Install nagios needed nrpe packages
  tags: monitoring
  yum: name={{ item }} state=latest
  with_items:
    - nrpe
    - nagios-plugins
    - nagios-plugins-disk
    - nagios-plugins-procs
    - nagios-plugins-load
  when: ansible_distribution == 'CentOS'

- name: 5666 port is open to monitor(s)
  command: firewall-cmd --permanent --zone=public --add-rich-rule="rule family='ipv4' source address='{{ item }}/32' port port=5666 protocol='tcp' accept"
  with_items: monitoring_hosts
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7'

- name: Bounce firewalld
  service: name=firewalld state=reloaded
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7'

- name: 5666 port is open to monitor(s) for centos6
  command: iptables -A INPUT -s {{ item }} -p tcp -m tcp --dport 5666 -m state --state NEW,ESTABLISHED -j ACCEPT
  with_items: monitoring_hosts
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '6'

- name: Save iptables for centos6
  command: service iptables save
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '6'

- name: flush iptables for centos6
  command: iptables --flush
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '6'
  
- name: restart iptables for centos6
  service: name=iptables state=restarted
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '6'
  
- name: Copy nrpe configuration file on host
  tags: 
    - monitoring
    - nrpe_checks
  template: src=nrpe.cfg.j2
            dest={{ nrpe_conf_path }}/nrpe.cfg backup=yes
            owner=root group=root mode=0644
  notify: restart nrpe

- name: Modify nrpe configuration itself
  tags: 
    - monitoring
    - nrpe_hosts
  lineinfile: dest=/etc/nagios/nrpe.cfg
              regexp="^allowed_hosts="
              line="allowed_hosts={{ nrpe_allowed_hosts }}"
              state=present
              backup=yes
  notify: restart nrpe

- name: Start and enable nrpe service
  tags: monitoring
  service: name=nrpe state=started enabled=yes
