---

- name: Install mongodb 4.0 repo
  copy: src=etc/yum.repos.d/mongodb-org-4.0.repo
        dest=/etc/yum.repos.d/mongodb-org-4.0.repo backup=no
        owner=root group=root mode=0644
  when: groups[cluster_group][0] == inventory_hostname
  tags:
    - ams_install
    - init_db

- name: Install mongoDB shell
  yum:
    name: mongodb-org-shell
    state: present
  when: groups[cluster_group][0] == inventory_hostname
  tags:
    - ams_install
    - init_db

- name: Move init roles script
  template: dest="/tmp/db_init_roles.js" owner=root group=root mode=640 src=db_init_roles.js.j2
  when: groups[cluster_group][0] == inventory_hostname
  tags:
    - ams_install
    - init_db
    - init_roles

- name: Run init roles script
  shell: mongo --host "rs0/{{ams_store_host}}" < /tmp/db_init_roles.js
  when: groups[cluster_group][0] == inventory_hostname
  tags:
    - ams_install
    - init_db
    - init_roles

- name: Move init projects script
  template: dest="/tmp/db_init_projects.js" owner=root group=root mode=640 src=db_init_projects.js.j2
  when: groups[cluster_group][0] == inventory_hostname
  tags:
    - ams_install
    - init_db
    - init_projects

- name: Run init projects script
  shell: mongo --host "rs0/{{ams_store_host}}" < /tmp/db_init_projects.js
  when: groups[cluster_group][0] == inventory_hostname
  tags:
    - ams_install
    - init_db
    - init_projects

- name: Move init users script
  template: dest="/tmp/db_init_users.js" owner=root group=root mode=640 src=db_init_users.js.j2
  when: groups[cluster_group][0] == inventory_hostname
  tags:
    - ams_install
    - init_db
    - init_projects

- name: Run init users script
  shell: mongo --host "rs0/{{ams_store_host}}" < /tmp/db_init_users.js
  when: groups[cluster_group][0] == inventory_hostname
  tags:
    - ams_install
    - init_db
    - init_projects

- name: Move init push worker script
  template: dest="/tmp/db_init_pushworker.js" owner=root group=root mode=640 src=db_init_pushworker.js.j2
  when: groups[cluster_group][0] == inventory_hostname
  tags:
    - ams_install
    - init_db
    - init_push_worker

- name: Run init push worker script
  shell: mongo --host "rs0/{{ams_store_host}}" < /tmp/db_init_pushworker.js
  when: groups[cluster_group][0] == inventory_hostname
  tags:
    - ams_install
    - init_db
    - init_push_worker


- name: AMS check - Version (1/3)
  uri:
    url: "https://localhost/v1/version"
    method: GET
    return_content: yes
    status_code: 200
    validate_certs: no
  retries: 3
  delay: 3
  register: ams_version_response
  tags:
    - ams_install
    - ams_check
    - ams_check:version

- name: AMS check - Health status (2/3)
  uri:
    url: "https://localhost/v1/status"
    method: GET
    return_content: yes
    status_code: 200
    validate_certs: no
  retries: 3
  delay: 3
  register: ams_status_response
  tags:
    - ams_install
    - ams_check
    - ams_check:stats

- name: AMS check - All projects (3/3)
  uri:
    url: "https://localhost/v1/projects?key={{ ams_service_token }}"
    method: GET
    return_content: yes
    status_code: 200
    validate_certs: no
  retries: 3
  delay: 3
  register: ams_projects_response
  tags:
    - ams_install
    - ams_check
    - ams_check:projects

