---

- name: Update argo-messaging package
  yum: name=argo-messaging state=latest enablerepo={{ repo_argo_enabled }} update_cache=yes
  notify: restart argo-messaging
  tags: ams_update

- name: Move init roles script
  template: dest="/tmp/db_init_roles.js" owner=root group=root mode=640 src=db_init_roles.js.j2
  tags: ams_update

- name: Run init roles script
  shell: mongo < /tmp/db_init_roles.js
  tags: ams_update

- name: Reload the systemd daemon
  systemd:
    daemon_reload: yes
  tags: ams_update