---

- name: Install mongoDB packages
  tags: mongoDB-packages
  yum: name={{ item }} state=present
  with_items:
    - mongodb-org-3.0.7
    - mongodb-org-server-3.0.7
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '6'

- name: Install mongoDB packages
  tags: mongoDB-packages
  yum: name={{ item }} state=present
  with_items:
    - mongodb-org
    - mongodb-org-server
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7'

- name: Bind mongod processes to one or more interfaces
  lineinfile: >
              dest=/etc/mongod.conf
              regexp="\ \ bindIp"
              line='  bindIp: {{ mongo_bind_interfaces }}'
              state=present
              backup=yes
  notify: restart mongo
  when: (ansible_distribution == 'CentOS' and ansible_distribution_major_version == '6') or (ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7')

- name: Fix issue with mongo init script
  lineinfile: >
              dest=/etc/mongod.conf
              regexp="\ \ pidFilePath"
              line='  pidFilePath: /var/run/mongodb/mongod.pid'
              state=present
              backup=yes
  notify: restart mongo
  when: (ansible_distribution == 'CentOS' and ansible_distribution_major_version == '6') or (ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7')

- name: Increase soft nproc limits
  copy: src=etc/security/limits.d/99-mongodb-nproc.conf
        dest=/etc/security/limits.d/99-mongodb-nproc.conf backup=no
        owner=root group=root mode=0644

- name: Enable and start mongoDB
  service: name=mongod enabled=yes state=started
