---

- name: Create cert_dir if not exists
  file: 
    dest: "{{cert_dir}}"
    state: directory
    owner: root
    group: root 
    mode: 0755

- name: Add ssl certificate chain file
  copy:
    src: private_files/{{inventory_hostname}}/{{httpd.chain}}
    dest: "{{cert_dir}}/{{httpd.chain}}"
  when: httpd.chain is defined

- name: Add ssl certificate file
  copy:
    src: private_files/{{inventory_hostname}}/{{httpd.cert}}
    dest: "{{cert_dir}}/{{httpd.cert}}"
  when: httpd.cert is defined

- name: Add ssl certificate key file
  copy:
    src: private_files/{{inventory_hostname}}/{{httpd.key}}
    dest: "{{cert_dir}}/{{httpd.key}}"
  when: httpd.key is defined
