---


- hosts: all
  become: yes
  roles:
    - { role: commons,                 task: timezone,        tags: timezone              }
    - { role: commons,                 task: repos,           tags: repos                 }
    - { role: commons,                 task: basic_utils,     tags: basic_utils           }
    - { role: commons,                 task: users,           tags: groups_users_sshKeys  }
    - { role: commons,                 task: sshd,            tags: sshd                  }
    - { role: commons,                 task: firewall,        tags: firewall              }
    - { role: commons,                 task: fail2ban,        tags: fail2ban_conf         }
    - { role: commons,                 task: cert,            tags: cert                  }
    - { role: commons,                 task: rsyslog,         tags: rsyslog_conf          }
    - { role: nickhammond.logrotate,                          tags: logrotate             }
    #- { role: commons,                 task: is_monitored,    tags: monitored             }
    #- { role: commons,                 task: backupamsmongo,  tags: rsyslog_conf          }

- hosts: mongo
  become: yes
  roles:
    - { role: mongodb,       task: main,    tags: mongodb       }

- hosts: apache
  become: yes
  roles:
    - { role: commons,    task: cert,    tags: apache_certs      }
    - { role: apache,     task: main,    tags: apache_install    }

- hosts: accounting
  become: yes
  roles:
    - { role: accounting,  task: accounting, tags: accounting }

- hosts: accounting_oidc_client
  become: yes
  roles:
    - { role: accounting, task: oidc_client, tags: accounting-oidc-client   }

- hosts: haproxy
  become: yes
  roles:
    - { role: haproxy, task: haproxy , tags: haproxy_install }

- hosts: icinga_agent
  become: yes
  roles:
    - { role: icinga_agent, tags: deploy_icinga_agent }