- hosts: all
  become: yes
  roles:
   - { role: commons, task: timezone, tags: timezone}
   - { role: commons, task: repos, tags: repos }
   - { role: commons, task: basic_utils, tags: basic_utils }
   - { role: commons, task: firewall, tags: firewall }
   - { role: commons, task: cert, tags: cert }
   - { role: commons, task: fail2ban, tags: fail2ban }
