---

- hosts: all
  become: yes
  roles:
    - { role: commons, task: firewall, tags: firewall }


- hosts: icinga_agent
  become: yes
  roles:
     - { role: icinga_agent, tags: deploy_icinga_agent }

