---

- hosts: all
  become: yes
  roles:
    - { role: commons, task: timezone, tags: timezone}
    - { role: commons, task: repos, tags: repos }
    - { role: commons, task: basic_utils, tags: basic_utils }
    - { role: commons, task: firewall, tags: firewall }
    - { role: commons, task: cert, tags: cert }
    - { role: commons, task: fail2ban, tags: fail2ban }
    - { role: nickhammond.logrotate, tags: logrotate}

- hosts: poem
  become: yes
  roles:
    - { role: poem, tags: poem}
    - { role: httpd, tags: httpd }

- hosts: haproxy
  become: yes
  roles:
    - { role: haproxy, task: rsyslog }
    - { role: haproxy, task: haproxy }

- hosts: ams_store
  become: yes
  roles:
    - { role: mongodb }
    - { role: ams, task: init_db, tags: ams_install }

- hosts: ams
  become: yes
  roles:
    - { role: private_hosts }
    - { role: zookeeper, tags: zookeeper_install }
    - { role: kafka, tags: kafka_install }
    - { role: ams, task: deploy, tags: ams_install }
    - { role: ams, task: deploy_metrics, tags: ams_install }

- hosts: authn
  become: yes
  roles:
    - { role: mongodb }
    - { role: argo-api-authn, task: authn-setup }
    - { role: argo-api-authn, task: ams-gocdb-users-create-script }

- hosts: metrics
  become: yes
  roles:
    - { role: metrics, task: ams-metrics-ui }
    - { role: metrics, task: ce_comp }
