---

- hosts: monitoring_engine
  sudo: true
  roles:
    - { role: firewall,           tags: firewall }
    - { role: repos,              tags: repos    }
    - { role: ca_bundle,          when: ca_bundle_install,   tags: ca_bundle }
    - { role: has_certificate,    tags: certificate }
    - { role: monitoring_engine,  tags: monitoring_engine }
