---

- hosts: monitoring_engine
  user: root
  roles:
    - { role: firewall, tags: firewall }
    - { role: repos,    tags: repos    }
    - { role: has_certificate, tags: certificate }
    - { role: monitoring_engine,    tags: monitoring_engine    }
