---


- hosts: all
  become: yes
  roles:
    - { role: commons,                 task: timezone,        tags: timezone              }
    - { role: commons,                 task: repos,           tags: repos                 }
    - { role: commons,                 task: basic_utils,     tags: basic_utils           }
    - { role: commons,                 task: users,           tags: groups_users_sshKeys  }
    - { role: commons,                 task: sshd,            tags: sshd                  }
    - { role: commons,                 task: firewall,        tags: firewall              }
    - { role: commons,                 task: fail2ban,        tags: fail2ban_conf         }
    - { role: commons,                 task: cert,            tags: cert                  }
    - { role: commons,                 task: rsyslog,         tags: rsyslog_conf          }
    - { role: nickhammond.logrotate,                          tags: logrotate             }
    #- { role: commons,                 task: is_monitored,    tags: monitored             }
    #- { role: commons,                 task: backupamsmongo,  tags: rsyslog_conf          }

- hosts: apache
  become: yes
  roles:
    - { role: commons,    task: cert,    tags: apache_certs      }
    - { role: apache,     task: main,    tags: apache_install    }

- hosts: quarkus-api
  become: yes
  roles:
    - { role: quarkus-api,  task: quarkus-api, tags: quarkus-api }

- hosts: icinga_agent
  become: yes
  roles:
    - { role: icinga_agent, tags: deploy_icinga_agent }

- hosts: icinga_agent
  become: yes
  roles:
    - { role: icinga_agent, tags: deploy_icinga_agent }
