---

- hosts: webapi
  become: yes
  roles:
    - { role: webapi, task: rollback }

- hosts: authn
  become: yes
  roles:
    - { role: argo-api-authn, task: rollback }

- hosts: ams
  become: yes
  roles:
    - { role: ams, task: rollback }
