---

- hosts: webapi
  become: yes
  roles:
    - { role: webapi, task: update }

- hosts: authn
  become: yes
  roles:
    - { role: argo-api-authn, task: update }
    - { role: argo-api-authn, task: python-env-setup }
    - { role: argo-api-authn, task: ams-create-users-gocdb-script }
    - { role: argo-api-authn, task: ams-create-users-cloud-info-script }

- hosts: ams
  serial: 1
  become: yes
  roles:
    - { role: ams, task: update }


- hosts: ams_push_server
  become: yes
  roles:
    - { role: push-server, task: update }
