---

- name: Install basic tools
  yum:
    name:
      - net-tools
      - vim
      - telnet
      - screen
      - lsof
    state: present
  tags: alerta

- name: Install python pip
  yum:
    name:
      - python-pip
    state: present
  tags: alerta

- name: Install mod_wsgi for httpd
  yum:
    name:
      - mod_wsgi
    state: present
  tags: alerta

- name: Install mod_ssl for httpd
  yum:
    name:
      - mod_wsgi
    state: present
  tags: alerta

- name: Install httpd tools
  yum:
    name:
      - httpd-tools
    state: present
  tags: alerta

- name: Install Virtualenv
  tags: alerta
  pip:
    name: virtualenv
    state: present

- name: Install Alerta.
  tags: alerta
  pip:
    name:
      - alerta
      - alerta-server
    virtualenv: '{{ alerta_server_dir }}'

- name: Install Alerta-amq and Alerta-mailer
  tags: alerta
  shell: '{{alerta_server_dir}}/bin/pip2 install git+https://github.com/alerta/alerta-contrib.git#subdirectory=plugins/amqp'

- name: Install Alerta-amq and Alerta-mailer
  tags: alerta
  shell: '{{alerta_server_dir}}/bin/pip2 install git+https://github.com/alerta/alerta-contrib.git#subdirectory=integrations/mailer'



- name: Establish alertad service script
  template: src=alertad.service.j2 dest=/lib/systemd/system/alertad.service
  notify: reload systemctl
  tags: alerta

- name: create symlink for alerta.service
  tags: alerta
  file:
    src: /lib/systemd/system/alertad.service
    dest: /etc/systemd/system/alertad.service
    state: link

- name: Establish alerta-mailer service script
  template: src=alerta-mailer.service.j2 dest=/lib/systemd/system/alerta-mailer.service
  notify: reload systemctl
  tags: alerta

- name: create symlink for alerta-mailer.service
  tags: alerta
  file:
    src: /lib/systemd/system/alerta-mailer.service
    dest: /etc/systemd/system/alerta-mailer.service
    state: link

- name: create a directory for env options for alerta-mailer service
  file:
    path: '/etc/systemd/system/alerta-mailer.service.d'
    state: directory

- name: add enviroment options for alerta-mailer service
  template: src=alerta-mailer.service.env.j2 dest=/etc/systemd/system/alerta-mailer.service.d/override.conf
  notify: reload systemctl
  tags: alerta


- name: Setup alerta log directory
  tags: alerta
  file:
    path: '/var/log/alerta'
    state: directory

- name: configure alertad
  template: src=alertad.conf.j2 dest=/etc/alertad.conf
  tags: alerta

- name: configure alerta cli
  template: src=alerta.conf.j2 dest=/root/.alerta.conf
  tags: alerta

- name: configure alerta-mailer
  template: src=alertad.conf.j2 dest=/etc/.alerta-mailer.conf
  tags: alerta


- name: create alerta wsgi root
  tags: alerta
  file:
    path: '{{ alerta_wsgi_root_dir }}'
    state: directory


- name: deploy new httpd configuration file
  template: src=httpd.conf.j2 dest=/etc/httpd/conf/httpd.conf
  notify: restart httpd
  tags: alerta


- name: configure ssl.conf for aletra
  tags: alerta
  notify: restart httpd
  template:
    src: ssl.conf.j2
    dest: '/etc/httpd/conf.d/ssl.conf'
    mode: 0444

- name: configure non-ssl.conf for aletra
  tags: alerta
  notify: restart httpd
  template:
    src: non-ssl.conf.j2
    dest: '/etc/httpd/conf.d/non-ssl.conf'
    mode: 0444

- name: configure wsgi for alerta
  tags: alerta
  notify: restart httpd
  template:
    src: api.wsgi.j2
    dest: '{{ alerta_wsgi_root_dir }}/api.wsgi'
    mode: 0444

- name: Install git
  tags: alerta
  yum:
    name:
      - git
    state: present
  tags: alerta


- name: clean dashboard repo folder
  tags: alerta
  file:
    path: '{{ alerta_dashboard_dir }}'
    state: absent

- name: get alerta dashboard from git repo
  tags: alerta
  git:
    repo: '{{ alerta_dashboard_repo }}'
    dest: '{{ alerta_dashboard_dir }}'
    force: yes
    version: master

- name: Configure Alerta Dashboard
  tags: alerta
  template:
    src: config.js.j2
    dest: '{{ alerta_dashboard_dir }}/app/config.js'
    mode: 0444

- name: Open http port
  notify: reload firewalld
  tags: alerta
  firewalld:
    port: 80/tcp
    permanent: true
    state: enabled

- name: Open https port
  notify: reload firewalld
  tags: alerta
  firewalld:
    port: 443/tcp
    permanent: true
    state: enabled

- name: Open api port
  notify: reload firewalld
  tags: alerta
  firewalld:
    port: 8080/tcp
    permanent: true
    state: enabled

- name: Install argo-alert tools
  tags: alerta
  pip:
    name:
      - '{{argo_alert_repo}}'
    virtualenv: '{{ alerta_server_dir }}'
