---

db_path: /var/lib/poem/poemserv.db
db_user: test
db_pass: test123
db_mail: foo@example.com

poem_namespace: example.com.TEST
poem_gocdb_url: goc.egi.eu
poem_secret: bbc2ac55-e3aa-4b89-9038-e1acc4baf232
poem_debug: "True"
poem_timezone: Europe/Athens