---

- name: Rollback argo-web-api package to specific version
  yum: name=argo-web-api-{{ artifact_version }} state=present  enablerepo={{ repo_enabled_argo }} update_cache=yes allow_downgrade=yes
  notify: restart argo-web-api service
  tags: webapi_rollback

- name: Reload the systemd daemon
  systemd:
    daemon_reload: yes
  tags: webapi_rollback