---

- name: Update argo-web-api package
  yum: name=argo-web-api state=latest enablerepo={{ repo_enabled_argo }} update_cache=yes
  notify: restart argo-web-api service
  tags: webapi_update

- name: Reload the systemd daemon
  systemd:
    daemon_reload: yes
  tags: webapi_update