---

- name: Install requirements
  yum: name={{ item }} state=present
  with_items:
    - java-1.7.0-openjdk.x86_64
    - wget
    - unzip
  tags: install_requirements

- name: Install CAs metapackage
  yum: name=ca-policy-egi-core state=latest
  tags: install_ca_bundle
  notify: restart webui

- name: Copy files to setup HOME_LAVOISIER
  template: src={{ item }}.j2 dest=/etc/profile.d/{{ item }}
            owner=root group=root mode=0644
  with_items:
    - lavoisier.sh
    - lavoisier.csh

- name: Create download directory
  file: path={{ lavoisier_home }} state=directory

- name: Create cache directory
  file: path={{ cache_directory }} state=directory

- name: Download lavoisier zip file
  get_url: url=https://github.com/ARGOeu/{{ argo_web }}/archive/{{ branch_name }}.zip
           dest={{ lavoisier_home }}/{{ branch_name }}.zip
           mode=0640
  register: download_out
  notify: restart webui

- name: Stage old directory if download target has changed
  command: mv {{ argo_web }}-{{ branch_name }} {{ argo_web }}-{{ branch_name }}.old
           chdir={{ lavoisier_home }}
  when: download_out is defined and download_out.changed
  ignore_errors: True

- name: Unzip zip file
  command: unzip {{ branch_name }}.zip
           chdir={{ lavoisier_home }}
  when: download_out is defined and download_out.changed

- name: Copy etc/lavoisier-hidden.properties file
  template: src=lavoisier-hidden.properties.j2
            dest={{ lavoisier_home }}/{{ argo_web }}-{{ branch_name }}/etc/lavoisier-hidden.properties
            owner=root group=root mode=0644
  notify: restart webui

- name: Copy etc/argo-config.properties file
  template: src=argo-config.properties.j2
            dest={{ lavoisier_home }}/{{ argo_web }}-{{ branch_name }}/etc/argo-config.properties
            owner=root group=root mode=0644
  notify: restart webui

- name: Configure etc/security/passwords.properties
  lineinfile: dest={{ lavoisier_home }}/{{ argo_web }}-{{ branch_name }}/etc/security/passwords.properties
              line='admin={{ admin_password_md5 }}'
              regexp='^admin'
              state=present
  notify: restart webui

- name: Start webui
  command: ./bin/lavoisier.sh start
           chdir={{ lavoisier_home }}/{{ argo_web }}-{{ branch_name }}
  ignore_errors: True
