---

- name: Install requirements
  yum: name={{ item }} state=present
  with_items:
    - java-1.8.0-openjdk.x86_64
    - wget
    - unzip
    - git
  tags: install_requirements

- name: Install CAs metapackage
  yum: name=ca-policy-egi-core state=latest
  tags: install_ca_bundle
  notify: restart webui

- name: Copy files to setup HOME_LAVOISIER
  template: src={{ item }}.j2 dest=/etc/profile.d/{{ item }}
            owner=root group=root mode=0755
  with_items:
    - lavoisier.sh
    - lavoisier.csh

- name: Create download directory
  file: path={{ lavoisier_home }} state=directory

- name: Clear cache directory
  command: rm -rf {{ cache_directory }} 
  ignore_errors: True

- name: Create cache directory
  file: path={{ cache_directory }} state=directory

- name: WEB-UI | Clone/Pull repo
  tags: 
   - webui
   - webui-shell
  git:
    repo: https://github.com/ARGOeu/argo-egi-web.git #"{{repository}}"
    dest: '{{lavoisier_home}}{{ argo_web }}'
    version: '{{branch_name}}'
    recursive: yes
    force: yes
    update: yes
  register: git_finished
  
- name: WEB-UI | fetch origin branch_name. Ensure local repo is actually up to date
  tags: 
   - webui
   - webui-shell
  shell: cd {{lavoisier_home}}{{ argo_web }} &&  git pull origin devel 

- name: Create logs directory
  file: path={{ lavoisier_home }}{{ argo_web }}/jsw/lavoisier/logs/ state=directory
  
- name: Copy etc/lavoisier-hidden.properties file
  tags: argo_config
  template: src=lavoisier-hidden.properties.j2
            dest={{ lavoisier_home }}{{ argo_web }}/etc/lavoisier-hidden.properties
            owner=root group=root mode=0644
  notify: restart webui

- name: Copy etc/argo-config.properties file
  tags: argo_config
  template: src=argo-config.properties.j2
            dest={{ lavoisier_home }}{{ argo_web }}/etc/argo-config.properties
            owner=root group=root mode=0644
  notify: restart webui
  
- name: Copy etc/lavoisier-service.properties file
  tags: argo_config
  template: src=lavoisier-service.properties.j2
            dest={{ lavoisier_home }}{{ argo_web }}/etc/lavoisier-service.properties
            owner=root group=root mode=0644
  notify: restart webui

- name: Configure etc/security/passwords.properties
  lineinfile: dest={{ lavoisier_home }}/{{ argo_web }}/etc/security/passwords.properties
              line='admin={{ admin_password_md5 }}'
              regexp='^admin'
              state=present
  notify: restart webui

- name: Start webui
  command: ./bin/lavoisier.sh start
           chdir={{ lavoisier_home }}/{{ argo_web }}
  ignore_errors: True
