---

# Based on
# https://github.com/hpcloud-mon/ansible-zookeeper
zookeeper_log_level: WARN
zookeeper_maxClientCnxns: 60
zookeeper_client_port: 2181
zookeeper_hosts: "{{ansible_fqdn}}:2181"
zookeeper_version: 3.4.6
zookeeper_url: https://archive.apache.org/dist/zookeeper/zookeeper-{{zookeeper_version}}/zookeeper-{{zookeeper_version}}.tar.gz
zookeeper_dir: /opt/zookeeper-{{zookeeper_version}}
zookeeper_data_dir: /var/lib/zookeeper
zookeeper_log_dir: /var/log/zookeeper
zookeeper_conf_dir: "{{ zookeeper_dir }}/conf"
