---
# tasks file for Apache Kafka system configurations


# System groups & users.

- name: "Ensure group '{{ kafka_group }}' exists"
  group:
    name: "{{ kafka_group }}"
    system: yes
  tags:
    - kafka
    - kafka-config
    - kafka-install
    - kafka-system
    - kafka-group

- name: "Ensure user '{{ kafka_user }}' exists"
  user:
    name: "{{ kafka_user }}"
    group: "{{ kafka_group }}"
    create_home: no
    system: yes
    comment: Apache Kafka user
  tags:
    - kafka
    - kafka-config
    - kafka-install
    - kafka-system
    - kafka-user


# Directories

- name: "Create {{ kafka_log_dirs }} directory for Apache Kafka DATA if it does not exist"
  file:
    path: "{{ kafka_log_dirs }}"
    state: directory
    owner: "{{ kafka_user }}"
    group: "{{ kafka_group }}"
    mode: '0755'
    recurse: yes
  tags:
    - kafka
    - kafka-config
    - kafka-install
    - kafka-system
    - kafka-disk
    - kafka-data_directory
    - kafka-create-data-directory


- name: "Create  /etc/kafka/   directory for Apache config files if it does not exist"
  file:
    path: "/etc/kafka/conf"
    state: directory
    owner: "{{ kafka_user }}"
    group: "{{ kafka_group }}"
    mode: '0755'
    recurse: yes
  tags:
    - kafka
    - kafka-config
    - kafka-install
    - kafka-system
    - kafka-config-directory


- name: "Set appropriate ownership, group and permissions in {{ kafka_root }}"
  file:
    path: "{{ kafka_root }}"
    state: directory
    owner: "{{ kafka_user }}"
    group: "{{ kafka_group }}"
    mode: '0755'
    recurse: yes
  tags:
    - kafka
    - kafka-config
    - kafka-install
    - kafka-system
    - kafka-disk


- name: "Create {{ kafka_logs }} directory for Apache Kafka logs if it does not exist"
  file:
    path: "{{ kafka_logs }}"
    state: directory
    owner: "{{ kafka_user }}"
    group: "{{ kafka_group }}"
    mode: '0755'
  tags:
    - kafka
    - kafka-config
    - kafka-install
    - kafka-logs

- name: Script for daily housekeeping of the logs directory
  template:
    src: kafka-logs-daily-housekeeping.sh.j2
    dest: "{{ kafka_scripts_dir }}/kafka-logs-daily-housekeeping.sh"
    owner: root
    group: root
    mode: '0755'
    backup: yes
  tags:
    - kafka
    - kafka-logs-scripts
    - kafka-logs-scripts-daily-housekeeping

- name: "Set up daily cron for kafka-logs-daily-housekeeping.sh"
  cron:
    cron_file: kafka-logs-daily-housekeeping
    name: "Set up daily cron for kafka-logs-daily-housekeeping.sh"
    user: root
    special_time: daily
    job: "{{ kafka_scripts_dir }}/kafka-logs-daily-housekeeping.sh"
  tags:
    - kafka
    - kafka-logs-scripts-cron
    - kafka-logs-scripts-daily-housekeeping-cron

- name: Script for monthly archival of the rotated logs
  template:
    src: kafka-logs-monthly-archive.sh.j2
    dest: "{{ kafka_scripts_dir }}/kafka-logs-monthly-archive.sh"
    owner: root
    group: root
    mode: '0755'
    backup: yes
  tags:
    - kafka
    - kafka-logs-scripts
    - kafka-logs-monthly-archive

- name: "Set up monthly cron for kafka-logs-monthly-archive.sh"
  cron:
    cron_file: kafka-logs-monthly-archive
    name: "Set up monthly cron for kafka-logs-monthly-archive.sh"
    user: root
    special_time: monthly
    job: "{{ kafka_scripts_dir }}/kafka-logs-monthly-archive.sh"
  tags:
    - kafka
    - kafka-logs-scripts-cron
    - kafka-logs-scripts-monthly-archive-cron

- name: Script for 6 months logs removal
  template:
    src: kafka-logs-6-months-remove.sh.j2
    dest: "{{ kafka_scripts_dir }}/kafka-logs-6-months-remove.sh"
    owner: root
    group: root
    mode: '0755'
    backup: yes
  tags:
    - kafka
    - kafka-logs-scripts
    - kafka-logs-remove

- name: "Set up monthly cron for kafka-logs-6-months-remove.sh"
  cron:
    cron_file: kafka-logs-6-months-remove
    name: "Set up monthly cron for kafka-logs-6-months-remove.sh"
    user: root
    special_time: monthly
    job: "{{ kafka_scripts_dir }}/kafka-logs-6-months-remove.sh"
  tags:
    - kafka
    - kafka-logs-scripts-cron
    - kafka-logs-scripts-remove-cron

# System heap


# System SWAP
