---
# tasks file for Apache Kafka


- name: "Install OpenJDK Runtime Environment {{ java_version }}"
  yum:
    name: java-{{ java_version }}-openjdk
    state: present
  tags:
    - kafka
    - kafka:install
    - kafka:java


- name: Install some utilities
  yum:
    name:
      - wget
      - tar
      - net-tools
      - netcat
      #- ca-certificates
    state: latest
  tags:
    - kafka
    - kafka:install
    - kafka:utils


- name: Include configuration tasks
  include: "config.yml"
  tags:
    - kafka
    - kafka:config


- name: Include Apache Kafka tasks
  include: "kafka.yml"
  tags:
    - kafka
    - kafka:install

