---

- name: Register private connection uuid
  command: "nmcli -g GENERAL.CON-UUID  d show {{item}}"
  loop: "{{firewall_private_interfaces}}"
  register: firewall_private_uuids
  tags: firewall

- name: Set zone internal to connections on network managed private interfaces
  command: "nmcli connection modify {{item.stdout}} connection.zone internal"
  loop: "{{firewall_private_uuids.results}}"
  tags: firewall

- name: Clear firewall state
  file:
      path: "{{ item }}"
      state: absent
  with_items:
    - /etc/firewalld/services
    - /etc/firewalld/zones
    - /etc/firewalld/helpers
    - /etc/firewalld/icmptypes
    - /etc/firewalld/ipsets
    - /etc/firewalld/direct.xml
  tags:
    - firewall
    - clear_firewalld
  notify: restart firewall

- name: Add default services to public zone
  firewalld:
    zone: public
    service: "{{item}}"
    permanent: true
    state: enabled
  with_items:
    #- ssh
    - dhcpv6-client
  tags:
    - firewall
    - add_services_to_public_zone
  notify: restart firewall

- meta: flush_handlers

- name: Create firewall new zones
  command: firewall-cmd --permanent --new-zone="{{item}}"
  with_items: "{{firewall_zones}}"
  notify: restart firewall
  tags:
    - firewall
    - create_new_zones
  register: new_zone_result
  failed_when: new_zone_result is failed and "NAME_CONFLICT" not in new_zone_result.stderr
  changed_when: new_zone_result is changed and "NAME_CONFLICT" not in new_zone_result.stderr

- name: Create firewall new services
  command: firewall-cmd --permanent --new-service="{{item.name}}"
  with_items: "{{firewall_services}}"
  notify: restart firewall
  tags:
    - firewall
    - create_new_services
  register: new_service_result
  failed_when: new_service_result is failed and "NAME_CONFLICT" not in new_service_result.stderr
  changed_when: new_service_result is changed and "NAME_CONFLICT" not in new_service_result.stderr

- name: Add port to services
  command: firewall-cmd --permanent --service="{{item.name}}" --add-port={{item.port}}
  with_items: "{{firewall_services}}"
  notify: restart firewall
  tags:
    - firewall
    - add_port_to_services
  ignore_errors: true

- name: Firewall add services to zones
  firewalld:
    zone: "{{item.zone}}"
    service: "{{item.service}}"
    permanent: true
    state: enabled
  with_items: "{{firewall_services_zones}}"
  tags:
    - firewall
    - add_services_to_zones
  notify: restart firewall

- name: Add sources to zones
  firewalld:
    zone: "{{item.zone}}"
    source: "{{item.source}}"
    permanent: true
    state: enabled
  with_items: "{{firewall_sources}}"
  tags:
    - firewall
    - add_sources_to_zones
  notify: restart firewall

- name: Add interfaces to zones
  firewalld:
    zone: "{{item.zone}}"
    interface: "{{item.interface}}"
    permanent: true
    state: enabled
  with_items: "{{firewall_interfaces}}"
  tags:
    - firewall
    - add_interfaces_to_zones
  notify: restart firewall


- name: Remove ssh service from public zone
  firewalld:
    zone: public
    service: "ssh"
    permanent: true
    state: disabled
  tags:
    - firewall
    - remove_ssh_from_public
  notify: restart firewall
