---

- name: Install argo repository definitions
  tags: repo_argo
  template: src=argo.repo.j2
            dest=/etc/yum.repos.d/argo.repo backup=no
            owner=root group=root mode=0644

- name: Install mongodb 3.2 repo
  tags: repo_mongodb
  copy: src=etc/yum.repos.d/mongodb-org-3.2.repo
        dest=/etc/yum.repos.d/mongodb-org-3.2.repo backup=no
        owner=root group=root mode=0644
  when: repo_mongo


- name: Install EGI-trustanchors repository definitions
  tags: repo_ca_bundle
  copy: src=etc/yum.repos.d/EGI-trustanchors.repo
        dest=/etc/yum.repos.d/EGI-trustanchors.repo backup=no
        owner=root group=root mode=0644
  when: ca_bundle

- name: Install UMD repo
  tags: repo_umd
  yum: name=http://repository.egi.eu/sw/production/umd/3/sl6/x86_64/updates/umd-release-3.0.1-1.el6.noarch.rpm
       state=present
  when: repo_umd

- name: Install promoo repo
  tags: repo_cloudera
  copy: src=etc/yum.repos.d/cloudera.repo
        dest=/etc/yum.repos.d/cloudera.repo backup=no
        owner=root group=root mode=0644
  when: repo_cloudera

- name: Install promoo repo
  tags: repo_monbox
  copy: src=etc/yum.repos.d/promoo.repo
        dest=/etc/yum.repos.d/promoo.repo backup=no
        owner=root group=root mode=0644
  when: repo_promoo

- name: Install rocci repo
  tags: repo_monbox
  copy: src=etc/yum.repos.d/rocci.repo
        dest=/etc/yum.repos.d/rocci.repo backup=no
        owner=root group=root mode=0644
  when: repo_rocci

- name: Install qcg repo
  tags: repo_monbox
  copy: src=etc/yum.repos.d/qcg.repo
        dest=/etc/yum.repos.d/qcg.repo backup=no
        owner=root group=root mode=0644
  when: repo_qcg

- name: Install unicore repo
  tags: repo_monbox
  copy: src=etc/yum.repos.d/unicore-7.repo
        dest=/etc/yum.repos.d/unicore-7.repo backup=no
        owner=root group=root mode=0644
  when: repo_unicore
