---

- name: Install argo-api-authn package
  yum:
    name: argo-api-authn
    state: latest
    enablerepo: "{{ repo_enabled_argo }}"
    update_cache: true
  tags: authn_install
  notify: restart argo-api-authn

- name: permissions for authn cert
  file:
    path: /etc/grid-security/hostcert.pem
    owner: argo-api-authn
    group: argo-api-authn
    mode: 0644
  tags: authn_install
  notify: restart argo-api-authn

- name: permissions for authn cert key
  file:
    path: /etc/grid-security/hostkey.pem
    owner: argo-api-authn
    group: argo-api-authn
    mode: 0644
  tags: authn_install
  notify: restart argo-api-authn

- name: template configuration for authn
  template:
    src: argo-api-authn-config.json.j2
    dest: /etc/argo-api-authn/conf.d/argo-api-authn-config.json
    owner: argo-api-authn
    group: argo-api-authn
    mode: 0644
  tags: authn_install

- name: Start argo-api-authn service
  service:
    name: argo-api-authn
    enabled: true
    state: started
  tags: authn_install
