---
<<<<<<< HEAD

- name: update connectors
  shell: yum -y makecache
  tags: 
    - connectors_config_main
    - connectors 

- name: update connectors
  shell: yum update -y argo-egi-connectors
  tags: 
    - connectors_config_main
    - connectors 

- name: Configure connectors
  tags: 
=======
  
- name: update connectors
  shell: yum -y makecache
  tags:
    - connectors_config_main
    - connectors

- name: update connectors
  yum:
    name: argo-egi-connectors
    state: latest
  tags:
    - connectors_config_main
    - connectors

- name: Creates directory
  file: path=/etc/argo-egi-connectors state=directory

- name: Configure connectors
  tags:
>>>>>>> [AO-387] : consumer update role
    - connectors_config_main
    - connectors_customer
    - connectors
  template: src=customer.conf.j2
            dest=/etc/argo-egi-connectors/{{ item.key | lower }}-customer.conf
            owner=root group=root mode=0644
            backup=yes
<<<<<<< HEAD
  with_dict: tenants
  
- name: Configure global connectors
  tags: 
=======
  with_dict: "{{ consumer_tenants }}"

- name: Configure global connectors
  tags:
>>>>>>> [AO-387] : consumer update role
    - connectors_config
    - connectors
    - connectors_global
  template: src=global.conf.j2
            dest=/etc/argo-egi-connectors/global.conf
            owner=root group=root mode=0644
            backup=yes
<<<<<<< HEAD
  with_dict: tenants
=======
  with_dict: "{{ consumer_tenants }}"
>>>>>>> [AO-387] : consumer update role

- name: POEM configuration
  tags:
    - connectors_config
    - poem_config
    - connectors
  template: src=poem-connector.conf.j2
            dest=/etc/argo-egi-connectors/poem-connector.conf
            owner=root group=root mode=0644
<<<<<<< HEAD
            backup=yes
=======
            backup=yes
>>>>>>> [AO-387] : consumer update role
