---
####################
# Cron_jobs: Standalone cron jobs used a) for deployment and b) pause / start cron jobs
# if you want to use for pausing a job (ex. poem_cron) you should run 
# ansible-playbook standalone-pause.yml -vvv --extra-vars "cron_status=true" --tags poem_cron
####################


- name: Configure poem connector per tenant cron job
  tags: 
    - connectors_config
    - connectors
    - poem_cron
    - cron_jobs
  cron: cron_file=poem_{{ item.key | lower }}
        name=poem_{{ item.key | lower }}
        minute=2
        hour=0
        user=root 
        job="/usr/libexec/argo-egi-connectors/poem-connector.py {% if item.value.prefilter is not defined %} -np {% endif %} -c /etc/argo-egi-connectors/{{ item.key | lower }}-customer.conf"
        state=present disabled={{cron_status}}
  with_dict: tenants

- name: Configure topology connector per tenant cron job
  tags: 
    - connectors_config
    - connectors
    - topology_cron
    - cron_jobs
  cron: cron_file=topology_{{ item.key | lower }}
        name=topology_{{ item.key | lower }}
        minute=7
        hour=0
        user=root
        job="/usr/libexec/argo-egi-connectors/topology-gocdb-connector.py -c /etc/argo-egi-connectors/{{ item.key | lower }}-customer.conf"
        state=present disabled={{cron_status}}
  with_dict: tenants

- name: downtimes-connector cron job
  tags: 
    - connectors_config
    - connectors
    - downtimes_cron
    - cron_jobs
  cron: cron_file=downtimes_{{ item.key | lower }}
        name=downtimes_{{ item.key | lower }}
        minute=15
        hour=0
        user=root
        job="/usr/libexec/argo-egi-connectors/downtimes-gocdb-connector.py -c /etc/argo-egi-connectors/{{ item.key | lower }}-customer.conf -d $(date "+\%Y-\%m-\%d")"
        state=present disabled={{cron_status}}
  with_dict: tenants
  
- name: Configure weights connector per tenant cron job
  tags: 
    - connectors_config
    - connectors
    - weights_cron
    - cron_jobs
  cron: cron_file=weights_{{ item.key | lower }}
        name=weights_{{ item.key | lower }}
        minute={{item.value.cron_weight_minute}}
        hour=0
        user=root
        job="/usr/libexec/argo-egi-connectors/weights-vapor-connector.py -c /etc/argo-egi-connectors/{{ item.key | lower }}-customer.conf"
        state=present disabled={{cron_status}}
  with_dict: tenants

- name: Configure ar-compute job cycle hourly cron 
  tags: 
    - compute_config
    - compute_job_hourly
    - cron_jobs
  cron: cron_file=ar_job_cycle_hourly
        user=root
        name=ar_job_cycle_hourly
        state=present 
        minute=55
        hour=*/2
        job="/usr/libexec/ar-compute/bin/job_cycle.py -d $(/bin/date --utc  +\%Y-\%m-\%d)"
        disabled={{cron_status}}

- name: Configure ar-compute job cycle daily cron 
  tags:
    - compute_crons
    - compute_job_daily
    - compute_config
  cron: cron_file=ar_job_cycle_daily
        user=root
        name=job_cycle_daily
        state=present
        minute=0
        hour=0
        job="/usr/libexec/ar-compute/bin/job_cycle.py -d $(/bin/date --utc --date '-1 day' +\%Y-\%m-\%d)"
        disabled={{cron_status}}
        
- name: Add ar-compute poller hourly cron for tenant EGI
  tags: 
    - compute_crons
    - compute_poller_hourly
    - cron_jobs
  cron: cron_file=ar_poller_hourly_egi
        name=ar_poller_hourly_egi
        minute=25
        hour=*
        user=root
        job="/usr/libexec/ar-compute/bin/poller_ar.py -t EGI"
        state=present disabled={{cron_status}}
 