---

- name: Install avro from ar project
  tags: ar-packages
  yum: name=avro state=present enablerepo={{ enabled_argo_repo }}

- name: Install python-pip
  tags: ar-packages
  yum: name=python-pip state=present

- name: Upgrade pymongo to latest available version
  tags: ar-packages
  pip: name=pymongo state=latest

- name: Install egi consumer package from ar project
  tags: 
    - ar-packages
    - consumer_config
  yum: name=argo-egi-consumer state=latest enablerepo={{ enabled_argo_repo }}
  notify: restart all consumers

- name: Create consumer configuration directories
  file: path=/etc/argo-{{ item.key | lower }}-consumer
        state=directory
        owner=root group=root mode=0755
  with_dict: tenants
  notify: restart all consumers

- name: Copy metric avro specification for each tenant
  tags: 
    - consumer_config
  template: src=metric_data.avsc.j2
            dest=/etc/argo-{{ item.key | lower }}-consumer/metric_data.avsc
            owner=root group=root mode=0644
  with_dict: tenants
  notify: restart all consumers

- name: Create consumer output directories per tenant
  tags: consumer_config
  file: path=/var/lib/argo-{{ item.key | lower }}-consumer
        state=directory
        owner=arstats group=arstats mode=0755
  with_dict: tenants

- name: Consumer configuration
  tags: 
    - consumer_config
  template: src=consumer.conf.j2
            dest=/etc/argo-{{ item.key | lower }}-consumer/consumer.conf
            owner=root group=root mode=0644
  with_dict: tenants
  notify: restart all consumers

# TODO: Make following task tenant unaware
- name: Copy out init scripts for non egi consumers
  tags: 
    - consumer_config
  template: src=consumer.init.j2
            dest=/etc/init.d/argo-{{ item.key | lower }}-consumer
            owner=root group=root mode=0755
  with_dict: tenants
  when: item.key|lower != "egi"
  notify: restart all non egi consumers

# TODO: Make following task tenant unaware
- name: Create copies of python wrappers for non egi consumers
  tags: 
    - consumer_config
  file: path=/usr/bin/argo-{{ item.key | lower }}-wrapper-consumer.py
        state=link src=/usr/bin/argo-egi-consumer.py
  with_dict: tenants
  when: item.key|lower != "egi"

- name: Enable and start consumer services
  tags: 
    - consumer_config
  service: name=argo-{{ item.key | lower }}-consumer enabled=on state=started
  with_dict: tenants

- name: Install argo-egi-connectors from ar project
  tags: 
    - ar-packages
    - connectors
  yum: name=argo-egi-connectors state=latest enablerepo={{ enabled_argo_repo }}

- name: Configure connectors
  tags: 
    - connectors_config
    - connectors
  template: src=customer.conf.j2
            dest=/etc/argo-egi-connectors/{{ item.key | lower }}-customer.conf
            owner=root group=root mode=0644
            backup=yes
  with_dict: tenants

- name: POEM configuration
  tags:
    - connectors_config
    - poem_config
  template: src=poem-connector.conf.j2
            dest=/etc/argo-egi-connectors/poem-connector.conf
            owner=root group=root mode=0644
            backup=yes

- name: Configure poem connector per tenant cron job
  tags: 
    - connectors_config
    - connectors
    - poem_cron
  cron: cron_file=poem_{{ item.key | lower }}
        name=poem_{{ item.key | lower }}
        minute=2
        hour=0
        user=root
        job="/usr/libexec/argo-egi-connectors/poem-connector.py -c /etc/argo-egi-connectors/{{ item.key | lower }}-customer.conf"
        state=present
  with_dict: tenants

- name: Configure poem connector per tenant cron job
  tags: 
    - connectors_config
    - connectors
    - topology_cron
  cron: cron_file=topology_{{ item.key | lower }}
        name=topology_{{ item.key | lower }}
        minute=7
        hour=0
        user=root
        job="/usr/libexec/argo-egi-connectors/topology-gocdb-connector.py -c /etc/argo-egi-connectors/{{ item.key | lower }}-customer.conf"
        state=present
  with_dict: tenants

- name: Install ar-compute from ar project
  tags: ar-packages
  yum: name=ar-compute state=latest enablerepo={{ enabled_argo_repo }}

- name: Copy out compute engine configuration file
  tags: ce_config
  template: src=ar-compute-engine.conf.j2
            dest=/etc/ar-compute-engine.conf
            owner=root group=root mode=0644
            backup=yes

- name: Configure ar-compute job cycle daily cron 
  tags: compute_config
  cron: cron_file=ar_job_cycle_daily
        user=root
        name=job_cycle_daily
        state=present
        minute=0
        hour=0
        job="/usr/libexec/ar-compute/bin/job_cycle.py -d $(/bin/date --utc --date '-1 day' +\%Y-\%m-\%d)"

- name: Configure ar-compute job cycle hourly cron 
  tags: compute_config
  cron: cron_file=ar_job_cycle_hourly
        user=root
        name=ar_job_cycle_hourly
        state=present
        minute=55
        hour=*/2
        job="/usr/libexec/ar-compute/bin/job_cycle.py -d $(/bin/date --utc  +\%Y-\%m-\%d)"

- name: Add ar-compute poller hourly cron for tenant EGI
  tags: compute_crons
  cron: cron_file=ar_poller_hourly_egi
        name=ar_poller_hourly_egi
        minute=25
        hour=*
        user=root
        job="/usr/libexec/ar-compute/bin/poller_ar.py -t EGI"
        state=present

- name: Install ar-data-retention from ar project
  tags: ar-data-retention
  yum: name=ar-data-retention state=latest enablerepo={{ enabled_argo_repo }}

- name: Parametrize data retention policies
  tags: data_retention
  template: src=ar-data-retention.conf.j2
            dest=/etc/ar-data-retention/ar-data-retention.conf
            owner=root group=root mode=0644

