---
- name: restart httpd
  service: name=httpd state=restarted enabled=yes

- name: restart supervisord
  service: name=supervisord state=restarted enabled=yes

- name: reload systemctl
  shell: systemctl daemon-reload

- name: reload firewalld
  shell: firewall-cmd --reload
