---

- name: Install requirements
  yum: name={{ item }} state=present
  with_items:
    - vim
    - wget
    - unzip
    - python-pip
    - tmux
    - zsh
  tags: install_requirements

- name: Install EGI-trustanchors packages
  tags: trustanchors-packages
  yum: name=ca-policy-egi-core state=present
  
- name: Install poem package from argo repository
  yum: name=poem state=latest enablerepo={{ enabled_argo_repo }}  update_cache=yes
  tags: install_poem

- name: Create poem.ini file
  tags: install_poem_conf
  template: src=poem.ini.j2
            dest=/etc/poem/poem.conf backup=yes
            owner=root group=root mode=0644
            
- name: upload certificate 
  tags: poem_certificate
  copy: src=private_files/DigiCertCA.crt
        dest=/etc/pki/tls/certs/DigiCertCA.crt backup=yes
        owner=root group=root mode=0400
        
- name: Create ssl.conf file
  template: src=ssl.conf.j2
            dest=/etc/httpd/conf.d/ssl.conf backup=yes
            owner=root group=root mode=0644
            
- name: update aai metadata
  tags: poem_aai_metadata
  shell: wget {{AAI_metadata}} -O /etc/poem/metadata-checkin.xml 
  
- name: Run db creation script
  shell: poem-createdb creates={{ db_path }}

- name: Start and enable httpd service
  service: name=httpd state=started enabled=yes

- stat: path=/etc/grid-security/hostkey.pem
  tags: poem_certificate, poem_cert
  register: hostkey_file
  
- name: change hostkey permissions
  tags: poem_certificate, poem_cert
  file: path=/etc/grid-security/hostkey.pem  mode=0404 
  when: hostkey_file.stat.exists