---

- name: Install CAs metapackage
  yum: name=ca-policy-egi-core state=latest
  tags: install_ca_bundle

- name: Install poem package from argo repository
  yum: name=poem state=latest enablerepo={{ enabled_argo_repo }}

- name: Create poem.ini file
  template: src=poem.ini.j2
            dest=/etc/poem/poem.ini backup=yes
            owner=root group=root mode=0644

- name: Run db creation script
  shell: poem-createdb creates={{ db_path }}

- name: Start and enable httpd service
  service: name=httpd state=started enabled=yes

