---

- name: Install requirements
  yum: name={{ item }} state=present
  with_items:
    - vim
    - wget
    - unzip
    - python-pip
    - tmux
    - zsh
  tags: install_requirements

- name: Install poem package from argo repository
  yum: name=poem state=latest enablerepo={{ enabled_argo_repo }}  update_cache=yes
  tags: install_poem

- name: Create poem.ini file
  template: src=poem.ini.j2
            dest=/etc/poem/poem.ini backup=yes
            owner=root group=root mode=0644

- name: Create ssl.conf file
  template: src=ssl.conf.j2
            dest=/etc/httpd/conf.d/ssl.conf backup=yes
            owner=root group=root mode=0644

- name: Run db creation script
  shell: poem-createdb creates={{ db_path }}

- name: Start and enable httpd service
  service: name=httpd state=started enabled=yes

