---
# tasks file for poem

- name: clean yum 
  shell: yum clean all
  
- name: Install poem package from argo repository
  yum: name=poem state=latest enablerepo={{ enabled_argo_repo }}  update_cache=yes
  tags: install_poem

- name: Create poem.ini file
  tags: install_poem_conf
  template: src=poem.ini.j2
            dest=/etc/poem/poem.conf backup=yes
            owner=root group=root mode=0644
            
- name: create secret_key 
  shell: poem-genseckey -f /etc/poem/secret_key
  tags: poem_secret_key
  when: poem_secret_key.stat.islnk is not defined 

- name: fetch the secret_key
  fetch:
    src: /etc/poem/secret_key
    dest: ./private_files/{{inventory_hostname}}/secret_key
    flat: yes
  tags:poem_secret_key 

- name: copy secret_key 
  tags: poem_secret_key
  copy: src=private_files/{{inventory_hostname}}/secret_key
        dest=/etc/poem/secret_key
  when: poem_secret_key.stat.islnk is  defined 

- name: update aai metadata
  tags: poem_aai_metadata
  shell: wget {{AAI_metadata}} -O /etc/poem/metadata-checkin.xml 
