---
# defaults file for accounting


## Privileged user for accounting
#
accounting_user: accounting
accounting_group: accounting


# Directories
#
accounting_root_dir: /opt/accounting
accounting_conf_dir: /etc/accounting/conf.d
accounting_logs_dir: /var/log/accounting


# Parameters
#
#quarkus_oidc:
#  client_id: example-system
#  credentials_secret: 1234
#  auth_server_url: https://login-example.com/auth/realms/
#
#keycloak_server:
#  url: https://login-example.com/auth
#  realm: example
#  client_id: example-system-public

quarkus_authorization: true
