---

- name: Add nics to designated firewall zones
  command: firewall-cmd --zone={{item.name}} --add-interface={{item.nic}} --permanent
  with_items: '{{zones | default([])}}'

- name: Add ports/proto rules to firewall zones
  command: firewall-cmd --zone={{item.zone}} --add-port={{item.port}}/{{item.proto}} --permanent
  with_items: '{{zone_port_rules | default([])}}'

- name: Enable required services (services dict)
  command: firewall-cmd --zone=public --add-service={{item}} --permanent
  with_items: '{{services | default([])}}'

- name: Enable new services (new_services dict)
  command: firewall-cmd --new-service={{item.service}} --permanent
  with_items: '{{new_services | default([]) }}'

- name: Enable required services in internal zone (new_services dict)
  command: firewall-cmd --zone={{item.zone}} --add-service={{item.service}} --permanent
  with_items: '{{new_services | default([]) }}'

- name: Enable required ports (new_services_iptables dict)
  command: firewall-cmd --service={{item.service}} --add-port={{item.dport}}/{{item.proto}} --permanent
  with_items: '{{new_services_iptables | default([]) }}'

- name: Enable required ports (iptables_rules dict)
  command: firewall-cmd --zone=public --add-port={{item.dport}}/{{item.proto}} --permanent
  with_items: '{{iptables_rules | default([]) }}'
  tags: iptables


- name: Restart firewalld
  command: firewall-cmd --reload


- name: Restart firewalld
  command: systemctl restart firewalld
