---
# defaults file for commons

# firewall default vars
firewall_sources: []
firewall_interfaces: []
firewall_zones: []
firewall_services: []
firewall_services_zones: []

# firewall
cert_dir: /etc/grid-security/
cert_path: /etc/grid-security/hostcert.pem
cert_key_path: /etc/grid-security/hostkey.pem

#defaults for role repos

repo_enabled_argo: argo-devel #from which repo to get the packages (argo-devel or argo-prod)
repo_mongo: true # if you want to install mongo repository
ca_bundle: false # if you want to install EGI-trustanchors repository
repo_qcg: false
repo_unicore: false
repo_umd: false
repo_promoo: false
repo_rocci: false
