---
# tasks file for ams
- name: Run the equivalent of "apt-get update" as a separate step
  yum:
    update_cache: true

- name: Install reqired packages
  yum:
    name:
      - git
      - curl
      - wget

- name: Download npm
  get_url:
    url: https://rpm.nodesource.com/setup_17.x
    dest: /tmp/setup_17.x

- name: Install npm
  shell:
    bash /tmp/setup_17.x

- name: Install NodeJs
  yum:
    name:
      - nodejs

- name: Check clone repo dest directory is absent
  file:
      state: absent
      path: "{{ repo_path }}/"

- name: Clone a private repository
  git:
    repo: "{{ git_repo_url }}"
    dest: "{{ repo_path }}"
    version: "{{ repo_branch }}"
    force: true
    accept_hostkey: true

- name: Install packages based on package.json using the npm
  npm:
    path: "{{ repo_path }}"
    state: present

- name: Copy config
  copy:
    src: "private_files/{{ inventory_hostname }}/config.json"
    dest: "{{ repo_path }}/src/config.json"
    remote_src: false

- name: Copy .env
  copy:
    src: "private_files/{{ inventory_hostname }}/.env"
    dest: "{{ repo_path }}/.env"
    remote_src: false

- name: Copy favicon
  copy:
    src: "private_files/{{ inventory_hostname }}/favicon.ico"
    dest: "{{ repo_path }}/public/favicon.ico"
    remote_src: false

- name: Copy logo
  copy:
    src: "private_files/{{ inventory_hostname }}/logo.svg"
    dest: "{{ repo_path }}/src/assets/logo.svg"
    remote_src: false

- name: Copy footer logo
  copy:
    src: "private_files/{{ inventory_hostname }}/footer_logo.svg"
    dest: "{{ repo_path }}/src/assets/footer_logo.svg"
    remote_src: false

- name: Build app
  command: npm run build
  args:
    chdir: "{{ repo_path }}"

- name: Copy folder to /var/www
  notify:
    - restart httpd
  copy:
    src: "{{ repo_path }}/dist/"
    dest: "/var/www/{{inventory_hostname}}/"
    remote_src: true
