---

- name: Install push server package
  yum:
    name: ams-push-server
    state: latest
    enablerepo: "{{ repo_enabled_argo }}"
    update_cache: true
  tags: push_install
  notify: restart ams-push-server

- name: copy cert to push-server folder
  copy: remote_src=yes src=/etc/grid-security/hostcert.pem dest=/var/www/ams-push-server/hostcert.pem backup=yes
      owner=ams-push-server group=ams-push-server mode=0644
  tags: push_install
  notify: restart ams-push-server

- name: copy key to push-server folder
  copy: remote_src=yes src=/etc/grid-security/hostkey.pem dest=/var/www/ams-push-server/hostkey.pem backup=yes
      owner=ams-push-server group=ams-push-server mode=0644
  tags: push_install
  notify: restart ams-push-server

- name: Create CA dir if not exists
  file: dest=/var/www/ams-push-server/cas state=directory
        owner=ams-push-server group=ams-push-server mode=0755
  tags: push_install
  notify: restart ams-push-server

- name: Copy CA file
  copy: src=private_files/{{ inventory_hostname }}/CA.crt
        dest=/var/www/ams-push-server/cas/CA.pem
        backup=yes
        owner=ams-push-server group=ams-push-server mode=0644
  tags: push_install
  notify: restart ams-push-server

- name: template configuration for the push server
  template:
    src: ams-push-server-config.json.j2
    dest: /etc/ams-push-server/conf.d/ams-push-server-config.json
    owner: ams-push-server
    group: ams-push-server
    mode: 0644
  tags: push_install
  notify: restart ams-push-server


- name: Allow bind port 443
  shell: setcap 'cap_net_bind_service=+ep' /var/www/ams-push-server/ams-push-server
  tags: push_install


- name: Configure argo-ams-push log(rsyslog)
  template:
   src: rsyslog_ams-push.conf.j2
   dest: /etc/rsyslog.d/ams-push.conf
   backup: true
  notify: restart rsyslog
  tags:
    - push_install
    - push_rsyslog


- name: Start the ams push server
  service:
    name: ams-push-server
    enabled: true
    state: started
  tags: push_install
