---
# tasks for icinga on CentOS Linux


## Package Repositories
# https://icinga.com/docs/icinga2/latest/doc/02-installation/#package-repositories
# https://packages.icinga.com/epel/
- name: Add Icinga repository to package management configuration.
  yum:
    name: "https://packages.icinga.com/epel/icinga-rpm-release-{{ ansible_distribution_major_version }}-latest.noarch.rpm"
    state: present
  tags:
    - icinga_agent
    - centos7
    - repository

- name: Enable EPEL repository.
  yum:
    name:
      - epel-release
    state: latest
  tags:
    - icinga_agent
    - centos7
    - repository

- name: Install Icinga 2.
  yum:
    name:
      - icinga2
    state: latest
  tags:
    - icinga_agent
    - centos7
    - packages


- name: Ensure icinga2 service is started and enabled on boot.
  service:
    name: icinga2
    state: started
    enabled: yes
  tags:
    - icinga_agent
    - centos7
    - packages


- name: Install Icinga 2 Check Plugins.
  yum:
    name:
      - nagios-plugins-all
      - nagios-plugins-check-updates
    state: latest
  tags:
    - icinga_agent
    - centos7
    - packages
    - nagios_plugins


- name: Install Argo External Plugins.
  yum:
    name: argo-external-tools
    state: latest
  tags:
    - icinga_agent
    - centos7
    - packages
    - argo_external_tools
    - icinga_external_tools


- name: Install Icinga 2 SELinux policy and some utils.
  yum:
    name:
      - icinga2-selinux
      - vim-icinga2
    state: latest
  notify: Restart Icinga 2 service
  tags:
    - icinga_agent
    - centos7
    - packages


- name: Install Mongo Agent Check.
  yum:
    name: percona-nagios-plugins
    state: latest
  tags: icinga_mongodb_agent
  when: ( repo_mongo_4x | default(false) | bool ) or ( repo_mongo | default(false) | bool )
  notify: Restart Icinga 2 service
