---

- name: Install argo-messaging package
  yum: name=argo-messaging state=latest enablerepo={{ enabled_argo_repo }} update_cache=yes
  notify: restart argo-messaging service
  tags: messaging_api

- name: systemctl daemon-reload to avoid message for disk rellocation
  command: systemctl daemon-reload
  ignore_errors: yes

- name: allow bind port 443
  shell: setcap 'cap_net_bind_service=+ep' /var/www/argo-messaging/argo-messaging
  tags: messaging_api
  
- name: Create directory 
  file: path={{ argo_msg_path }}certs state=directory mode=0755

- name: Configure argo-messaging api
  template: src=config.json.j2
            dest=/etc/argo-messaging/config.json backup=yes
            owner=root group=root mode=0644
  notify: restart argo-messaging service
  tags: messaging_api

- name: Start argo-messaging service
  service: name=argo-messaging state=started
  tags: messaging_api
