---

- name: Install argo-messaging package
  yum: name=argo-messaging state=latest enablerepo={{ enabled_argo_repo }}
  notify: restart argo-messaging service
  tags: messaging_api

- name: Configure argo-messaging api
  template: src=config.json.j2
            dest=/etc/argo-messaging/config.json backup=yes
            owner=root group=root mode=0644
  notify: restart argo-messaging service
  tags: messaging_api

- name: Start argo-messaging service
  service: name=argo-messaging state=started
  tags: messaging_api
