---
# handlers file for haproxy

- name: restart rsyslog
  service:
    name: rsyslog
    state: restarted
    enabled: true

- name: restart haproxy
  service:
    name: haproxy
    state: restarted
    enabled: true

