---
# handlers file for haproxy

- name: restart rsyslog
  service:
    name: rsyslog
    state: restarted
    enabled: yes

-   name: restart rsyslog
    service:
      name: rsyslog
      state: restared
