---

- name: Copy host x509 certificate onto host
  tags: certificate
  copy: src=hostcert.pem
        dest={{ cert_path }} backup=yes
        owner=root group=root mode=0644

- name: Copy host x509 key onto host
  tags: certificate
  copy: src=hostkey.pem
        dest={{ key_path }} backup=yes
        owner=root group=root mode=0400

- name: Create softlink (to cert) for API
  file: state=link
        src={{ cert_path }}
        path=/etc/pki/tls/certs/localhost.crt
  when: inventory_hostname in groups.standalone

- name: Create softlink (to key) for API
  file: state=link
        src={{ key_path }}
        path=/etc/pki/tls/private/localhost.key
  when: inventory_hostname in groups.standalone

