---
# handlers file for argo-api-authn

- name: restart argo-api-authn
  service:
    name: argo-api-authn
    state: restarted

- name: restart rsyslog
  service:
    name: rsyslog
    state: restarted

