---
ssmtp_debug: YES;
alerta_admin_list: ['admin@localhost']
alerta_plugin_list: ['reject','amqp']
alerta_allowed_env_list: ['production']
alerta_dashboard_dir: '/var/www/html/'
alerta_dashboard_repo: https://github.com/alerta/alerta-webui.git
alerta_dashboard_release: 'v7.2.11' 
alerta_amqp_release: '8b1b3b3'
alerta_mailer_release: '74834e6'
alerta_secret_key: 'HOf%A)w6de5oJXJ^F=Jb@rfz4YDRKui9'
alerta_server_dir: '/opt/alerta/'
alerta_token: ''


alerta_www_url: 'localhost'
alerta_www_alias: 'localhost'
alerta_main_mail: ''
alerta_mail_from: ''
alerta_smtp_host: ''
alerta_smtp_port: 587
alerta_mail_debug: true
alerta_version: 7.2.2
alerta_server_version: 7.2.11

# default: use pip to install argo-alert from github repo using devel branch
argo_alert_repo: 'git+https://github.com/ARGOeu/argo-alert@devel#egg=argoalert'

argo_alert_kafka: 'kafka.node.foo'

ca_bundle: true

cert_path: /etc/grid-security/hostcert.pem
cert_key_path: /etc/grid-security/hostkey.pem
cert_dir: /etc/grid-security/
ca_path_bundle: /etc/pki/tls/certs/ca-bundle.crt

alerta_tenants:
  foo:
    ui_endpoint: argo_ui_hostname
    contact_api_type: 'contact.api.type'
    contact_api_endpoint: 'https://contact.api.foo'
    mail_template: ~/alerta-foo.tmpl
    mail_template_html: ~/alerta-foo.html.tmpl
    mail_type: html
    mail_debug: true
    mail_rule: ~/alerta-foo/mail-rules/mail-foo-rules.json

smtp_debug: true
