---
mail_to : ''
mail_form: ''
smpt_username: ''
smpt_password: ''
alerta_secret: ''
alerta_token: ''
alerta_server_dir: '/opt/alerta'
alerta_wsgi_root_dir: '/var/www'
alerta_dashboard_dir: '/var/www/alerta'
alerta_dashboard_repo: https://github.com/alerta/angular-alerta-webui.git
www_url: 'localhost'
www_alias: 'localhost'

# default: use pip to install argo-alert from github repo using devel branch
argo_alert_repo: 'git+https://github.com/ARGOeu/argo-alert@devel#egg=argoalert'
