---
alerta_secret: ''
alerta_token: ''
alerta_server_dir: '/opt/alerta'
alerta_wsgi_root_dir: '/var/www'
alerta_dashboard_dir: '/var/www/alerta'
alerta_dashboard_repo: https://github.com/alerta/angular-alerta-webui.git
alerta_ui_release: 'v5.0.0'
alerta_amqp_release: 'cb04fb6'
alerta_mailer_release: 'e52f4f9'
alerta_www_url: 'localhost'
alerta_www_alias: 'localhost'
alerta_main_mail: ''
alerta_mail_from: ''
alerta_smtp_host: ''
alerta_smtp_port: 587
alerta_mail_debug: true
alerta_version: 5.0.10
alerta_server_version: 5.0.5

# default: use pip to install argo-alert from github repo using devel branch
argo_alert_repo: 'git+https://github.com/ARGOeu/argo-alert@devel#egg=argoalert'

argo_alert_kafka: 'kafka.node.foo'
argo_alert_token: 'secret_token'

ca_bundle: true

cert_path: /etc/grid-security/hostcert.pem
cert_key_path: /etc/grid-security/hostkey.pem
cert_dir: /etc/grid-security/
ca_path_bundle: /etc/pki/tls/certs/ca-bundle.crt

alerta_tenants:
  foo:
    ui_endpoint: argo_ui_hostname
    contact_api_type: 'contact.api.type'
    contact_api_endpoint: 'https://contact.api.foo'
    mail_template: ~/alerta-foo.tmpl
    mail_template_html: ~/alerta-foo.html.tmpl
    mail_type: html
    mail_debug: true
    mail_rule: ~/alerta-foo/mail-rules/mail-foo-rules.json
