---
# handlers file for commons

# handlers file for fail2ban
- name: restart fail2ban (with service)
  service:
    name: fail2ban
    state: restarted
  listen: "restart fail2ban"

- name: reload firewall
  command: "firewall-cmd --reload"

- name: restart firewall
  service:
    name: firewalld
    state: restarted
