---
# handlers file for commons

# handlers file for fail2ban
- name: restart fail2ban (with service)
  service:
    name: fail2ban
    state: restarted
  listen: "restart fail2ban"
  when: ansible_service_mgr != 'systemd'

- name: restart fail2ban (with systemd)
  systemd:
    name: fail2ban
    state: restarted
  listen: "restart fail2ban"
  when: ansible_service_mgr == 'systemd'
