---
# handlers file for commons

- name: restart fail2ban
  service:
    name: fail2ban
    state: restarted

- name: reload firewall
  command: "firewall-cmd --reload"

- name: restart firewall
  service:
    name: firewalld
    state: restarted

- name: restart sshd
  service:
    name: sshd
    state: restarted

- name: restart nrpe
  service:
    name: nrpe
    state: restarted

- name: restart rsyslog
  service:
    name: rsyslog
    state: restarted
    enabled: true

