---

- name: Install nginx, git, npm
  yum:
   name: "{{ item }}"
   state: present
  loop:
   - nginx
   - git
   - npm

- name: get the ams-metrics-ui repo
  git:
    repo: https://github.com/ARGOeu/ams-metrics-ui.git
    dest: /var/www/ams-metrics-ui

- name: create the config.js needed for the app
  template:
     src: ams-metrics-ui.config.j2
     dest: /var/www/ams-metrics-ui/src/config.js

- name: use npm to fetch dependencies
  shell: cd /var/www/ams-metrics-ui && npm i

- name: use npm to build the app
  shell: cd /var/www/ams-metrics-ui && npm run build .

- name: create nginx configuration file
  template:
     src: nginx.conf.j2
     dest: /etc/nginx/nginx.conf

- name: nginx enable
  service:
    name: nginx
    enabled: true
    state: started
