---
# tasks file for pcc-ui
- name: Run the equivalent of "apt-get update" as a separate step
  yum:
    update_cache: true

- name: Install reqired packages
  yum:
    name:
      - git
      - curl
      - wget

- name: Download npm
  get_url:
    url: https://rpm.nodesource.com/setup_17.x
    dest: /tmp/setup_17.x

- name: Install npm
  shell:
    bash /tmp/setup_17.x

- name: Install NodeJs
  yum:
    name:
      - nodejs

- name: Clone a private repository
  git:
    repo: "{{ git_repo_url }}"
    dest: "{{ repo_path }}"
    version: "{{ repo_branch }}"
    force: true
    accept_hostkey: true

- name: Install packages based on package.json using the npm
  npm:
    path: "{{ repo_path }}"
    state: present

- name: Copy config
  copy:
    src: "private_files/{{ inventory_hostname }}/config.js"
    dest: "{{ repo_path }}/src/config.js"
    remote_src: false

- name: Copy config
  copy:
    src: "private_files/{{ inventory_hostname }}/.htpasswd"
    dest: "/etc/httpd/.htpasswd"
    remote_src: false

- name: Build app
  command: npm run build
  args:
    chdir: "{{ repo_path }}"

- name: Copy folder to /var/www
  copy:
    src: "{{ repo_path }}/build/"
    dest: "/var/www/{{inventory_hostname}}/"
    remote_src: true
