---

- name: Copy nagios.cfg file
  template: src=nagios.cfg.j2
            dest=/etc/nagios/nagios.cfg
            owner=nagios group=nagios mode=0644
  notify: reload nagios
  tags:
    - monbox_config
    - monbox_config_nagios
    - monbox_config_nagios_cfg

- name: Copy cgi.cfg file
  template: src=cgi.cfg.j2
            dest=/etc/nagios/cgi.cfg
            owner=nagios group=nagios mode=0644
  notify: reload nagios
  tags:
    - monbox_config
    - monbox_config_nagios
    - monbox_config_nagios_cgi_cfg


- name: Create a cron job to restart apache
  cron: name=restart_httpd
        user="root"
        minute="53" hour="2,8,14,20"
        job="( /sbin/service httpd status && /sbin/service httpd graceful ) > /dev/null 2>&1"
  when: ca_bundle
  tags:
    - monbox_config
    - monbox_config_cronjob

- name: Create and copy ncg.conf file
  template: src=ncg.conf.j2
            dest=/etc/argo-ncg/ncg.conf
            owner=root group=root
  notify: reload nagios
  tags:
    - monbox_config
    - monbox_config_ncg

- name: Copy ncg.loacconf file
  copy:
    src: private_files/{{inventory_hostname}}/files/ncg.localdb
    dest: /etc/argo-ncg/ncg.localdb
  tags:
    - monbox_config
    - monbox_config_ncg
    - monbox_config_ncg_localdb
  ignore_errors: true

- name: Creates /etc/nagios/plugins/ directory
  file: path=/etc/nagios/plugins/ state=directory
  tags:
    - config
    - config-ncg

- name: Copy ncg.loacconf configuration files
  copy:
    src: private_files/{{inventory_hostname}}/files/plugins/
    dest: /etc/nagios/plugins/
  tags:
    - monbox_config
    - monbox_config_ncg
  ignore_errors: true

- name: Run ncg.reload
  command: ncg.reload.sh
  tags:
    - monbox_config
    - monbox_config_ncg

- name: Copy argo-nagios-ams-publisher - ams-publisher file
  template: src=ams-publisher.j2
            dest=/etc/argo-nagios-ams-publisher/ams-publisher.conf
            owner=nagios group=nagios
  tags:
    - monbox_config
    - monbox_config_ams_publisher

- name: Enable nagios on boot and start service
  service: name={{ item }} state=started enabled=yes
  with_items:
    - nagios
  tags:
    - monbox_config
    - monbox_config_enable_nagios

- name: Start fetch-crl cron
  service: name=fetch-crl-cron state=started enabled=yes
  when: ca_bundle
  tags:
    - monbox_config
    - monbox_config_enable_fetch_cron

- name: Start fetch-crl boot
  service: name=fetch-crl-boot state=started enabled=yes
  when: ca_bundle
  ignore_errors: true
  tags:
    - monbox_config
    - monbox_config_enable_fetch_cron

- name: Enable argo-nagios-ams-publisher on boot and start service
  service: name=ams-publisher state=started enabled=yes
  tags:
    - monbox_config
    - monbox_config_enable_ams
  ignore_errors: true

- name: Copy broker-list file
  template: src=broker-list.j2
            dest=/var/cache/msg/broker-cache-file/broker-list
            owner=root group=root mode=0644
  when: monbox_broker_host is defined
  tags:
    - monbox_config
    - monbox_config_enable_ams


- name: ensure file exists
  copy:
    content: ""
    dest: /etc/nagios/htpasswd.users
    force: false
    group: root
    owner: root
    mode: 0555

- name: Copy htpasswd.users configuration files
  copy:
    src: private_files/{{inventory_hostname}}/etc/nagios/htpasswd.users
    dest: /etc/nagios/htpasswd.users
  tags:
    - monbox_config
    - monbox_config_httpasswd
  ignore_errors: true

- name: Copy pem certificate to globus folder to check CERT validity
  copy: src=private_files/{{ inventory_hostname }}/{{ inventory_hostname }}.pem
        dest=/etc/nagios/globus/hostcert.pem backup=yes
        owner=nagios group=nagios
  tags:
    - monbox_config
